function esvm_get_closest_matches(models, imgsDir, topk)
% Gives 'topk' number of best matches to the e-svm 'models' from imgsDir
% @models : models generated by esvm_train_single_exemplar or voc etc
% @imgsDir : (string) path of corpus directory
% @topk : number of top results to return
%
% (c) Rohit Girdhar

endings = '((.jpg)|(.png)|(.gif)|(.JPEG)|(.JPG)|(.jpeg)|(.bmp))$';
frpaths = getAllFiles(imgsDir); % recursive search img files relative to imgsDir
imgFilesOrNot = regexp(frpaths, endings);
frpaths(cellfun(@isempty, imgFilesOrNot)) = []; % keep only image files

fullpaths = cellfun2(@(x) fullfile(imgsDir, x), frpaths);
%%% TODO (Rohit) : break this into chunks, can't read 10000s of images at
%%% once
imgset = cellfun2(@(x) imread(x), fullpaths);
params = esvm_get_default_params;
local_detections = esvm_detect_imageset(imgset, models, params);
result_struct = esvm_pool_exemplar_dets(local_detections, models, [], params);
allbbs = esvm_show_top_dets(result_struct, local_detections, ...
                              imgset, models, ...
                              params,  topk);
fprintf('%*s : score\n', 40, 'matching image name');
for i = 1 : size(allbbs, 1)
    fprintf('%*s : %0.5f\n', 40, frpaths{allbbs(i, 11)}, allbbs(i, 12));
end

