function esvm_get_closest_matches(models, imgsDir, topk)
% Gives 'topk' number of best matches to the e-svm 'models' from imgsDir
% @models : models generated by esvm_train_single_exemplar or voc etc
% @imgsDir : (string) path of corpus directory
% @topk : number of top results to return
%
% (c) Rohit Girdhar

endings = '((.jpg)|(.png)|(.gif)|(.JPEG)|(.JPG)|(.jpeg)|(.bmp))$';
frpaths = getAllFiles(imgsDir); % recursive search img files relative to imgsDir
imgFilesOrNot = regexp(frpaths, endings);
frpaths(cellfun(@isempty, imgFilesOrNot)) = []; % keep only image files

params = esvm_get_default_params;
fullpaths = cellfun2(@(x) fullfile(imgsDir, x), frpaths);
imgsChunkSize = 50; % read images in chunks of this size
numImgsDone = 0;
all_local_detections = {};
while numImgsDone < numel(fullpaths)
    fprintf('Chunk %d to %d\n', numImgsDone + 1, numImgsDone + imgsChunkSize);
    imgset = cellfun2(@(x) imread(x), ...
        fullpaths(numImgsDone + 1 : min(numImgsDone + imgsChunkSize, end)));
    local_detections = esvm_detect_imageset(imgset, models, params);
    local_detections = cellfun(@(x) {addToIndex(x, numImgsDone)}, local_detections);
    all_local_detections = [all_local_detections; local_detections];
    numImgsDone = numImgsDone + numel(imgset);
end
result_struct = esvm_pool_exemplar_dets(all_local_detections, models, [], params);
esvm_show_top_dets(result_struct, all_local_detections, ...
                              fullpaths, models, ...
                              params,  topk);

function [x] = addToIndex(x, numImgsDone)
x.index = x.index + numImgsDone;
