function esvm_get_closest_matches(models, imgsDir, topk)
% Gives 'topk' number of best matches to the e-svm 'models' from imgsDir
% @models : models generated by esvm_train_single_exemplar or voc etc
% @imgsDir : (string) path of corpus directory
% @topk : number of top results to return
%
% (c) Rohit Girdhar

endings = '((.jpg)|(.png)|(.gif)|(.JPEG)|(.JPG)|(.jpeg)|(.bmp))$';
frpaths = getAllFiles(imgsDir); % recursive search img files relative to imgsDir
imgFilesOrNot = regexp(frpaths, endings);
frpaths(cellfun(@isempty, imgFilesOrNot)) = []; % keep only image files

params = esvm_get_default_params;
fullpaths = cellfun2(@(x) fullfile(imgsDir, x), frpaths);
local_detections = esvm_detect_imageset(fullpaths, models, params);
result_struct = esvm_pool_exemplar_dets(local_detections, models, [], params);
params.dataset_params.localdir = 'res';
[~, imgs_dirname, ~] = fileparts(imgsDir);
esvm_show_top_dets(result_struct, local_detections, ...
                              fullpaths, models, ...
                              params,  topk, imgs_dirname);

